version: "3.10"
services:
  rabbitmq:
    hostname: "rabbitmq"
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    stdin_open: true
    tty: true
    # networks:
    #   - my-network
    # environment:
    #   - RABBITMQ_DEFAULT_USER=rabbitmquser
    #   - RABBITMQ_DEFAULT_PASS=some_password 

  sender:
    image: 'sender'
    container_name: 'sender'
    build: ./sender/
    ports:
      - "8000:8000"
    command: node emit_log_direct.js
    stdin_open: true
    tty: true
    depends_on:
      - "rabbitmq"
    # networks:
    #   - my-network

  receiver:
    image: 'receiver'
    container_name: 'receiver'
    build: ./receiver/
    ports:
      - "8001:8001"
    command: "node receive_logs_direct.js info"
    stdin_open: true
    tty: true
    depends_on:
      - "rabbitmq"
    # networks:
    #   - my-network

networks:
  my-network:
    driver: bridge