version: "3.10"
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq

  sender:
    image: 'sender'
    container_name: 'sender'
    build: ./sender/
    ports:
      - "8000:8000"
    command: node emit_log_direct.js
    depends_on:
      rabbitmq:
        condition: "service_healthy"
    

  receiver:
    image: 'receiver'
    container_name: 'receiver'
    build: ./receiver/
    ports:
      - "8001:8001"
    command: "node receive_logs_direct.js info"
    depends_on:
      rabbitmq:
        condition: "service_healthy"
